name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          ./render.sh
        working-directory: plant-uml

      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
#          file: "**/*.svg"
          file: "plant-uml/**/*.svg"
          overwrite: true
          verbose: true
          update_latest_release: true
